name: Bug Report | 🐛
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["constellation-mc/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before proceeding, please make sure to do this first. 📋
        - Ensure you are running the **latest** version.
        - A similar issue hasn't been filled before.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    attributes:
      label: Logs
      description: |
        If available, add logs to help identify your problem.
        Please upload your log to [Github Gist](https://gist.github.com/), [mslo.gs](https://mclo.gs/) or any other pasting platform.
    validations:
      required: false
  - type: input
    id: mod-version
    attributes:
      label: Version
      description: What version are you running?
    validations:
      required: true
