name: Feature Request | ✨
description: Request something to be implemented.
title: "[Request]: "
labels: ["enhancement"]
projects: ["constellation-mc/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Before proceeding, please make sure to do this first. 📋
        - Check that a simmilar request hasn't been made before.
  - type: textarea
    attributes:
      label: What would you like to see added?
      placeholder: "I want..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Images
      description: If possible, add images to help explain your request.
    validations:
      required: false
